<?php

return [
    'skip-route-function' => true,
    'groups' => [
        'auth' => [
            'auth.*',
            'settings.*',
            'locale.*',
            'global.*',
            'ip.*',
            'token.*',
        ],
        'admin' => [
            'auth.*',
            'admin.*',
            'coin-adapters.*',
            'wallets.*',
            'locale.*',
            'user.*',
            'user-profile.*',
            'settings.*',
            'ip.*',
            'grid.*',
            'global.*',
            'token.*',
        ],
        'index' => [
            'auth.*',
            'page.*',
            'admin.user.*',
            'admin.role.*',
            'email-verification.send',
            'exchange-trade.*',
            'exchange-swap.*',
            'exchange-swaps.*',
            'commerce-account.*',
            'commerce-transaction.*',
            'commerce-customer.*',
            'commerce-payment.*',
            'locale.*',
            'user.*',
            'user-profile.*',
            'settings.*',
            'ip.*',
            'grid.*',
            'global.*',
            'wallets.*',
            'unused-wallets.*',
            'transfer-records.*',
            'wallet-account.*',
            'token.*',
            'feature-limit.*',
            'stake-plan.*',
            'stake.*',
            'payment.*',
            'peer-payment.*',
            'peer-payment-method.*',
            'peer-offer.*',
            'peer-trade.*',
            'bank.*',
            'bank-account.*',
        ],
        'installer' => [
            'installer.*',
        ],
    ],
];
